# Generated by Django 2.2.6 on 2019-11-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='treatmen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('doctor', models.CharField(max_length=20)),
                ('treatments', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('appointment', models.BooleanField(default=False)),
            ],
        ),
    ]
